Host: 1274911913
Robot: 1556566021
Debug: Flase
#工具群1.2
DebugGroup: 
  - 962618214
  - 1103511016
#1.2.3.4.5群 服务器 千欣
group:
  - 962618214 
  - 1103511016 
  - 234861263 
  - 912779948
  - 473845651
  - 566328546
  - 960879609
Permission:
  1274911913: root
  1556566021: bot
image:
  YY_yyds: images/YYS.jpg
#柚子社天下第二()