Host: 1274911913
Robot: 1556566021
#工具群1.2
DebugGroup: 
  - 962618214
  - 1103511016
Group:
  - 962618214 
  - 1103511016 
  - 234861263 
  - 912779948
  - 473845651
  - 566328546
  - 960879609
MCBE_Service: 566328546
Permission:
  1274911913: root
  1556566021: bot
image:
  YY_yyds: images/YYS.jpg